# Generated by Django 3.0.5 on 2020-04-15 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booktitle', models.CharField(max_length=200)),
                ('yes24_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='bookrank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('bookcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gather_rank.bookcode')),
            ],
        ),
        migrations.CreateModel(
            name='bookdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('published_date', models.CharField(max_length=50)),
                ('bookcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gather_rank.bookcode')),
            ],
        ),
    ]
